api_platform:
    title: API voiture reservation
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
